## docker-compose.yml

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_net
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server
    stdin_open: true
    tty: true

  mysql_server:
      image: mysql:8.0
      networks:
        - my_net
      ports:
        - "3305:3306"
      volumes:
        - ./db/data:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=studydb
        - MYSQL_USER=root
        # - MYSQL_PASSWORD=7375
        - MYSQL_ROOT_PASSWORD=7375

networks:
  my_net:

